<?xml version="1.0" encoding="UTF-8"?>
<Export generator="Cache" version="25" zv="Cache for Windows (x86-64) 2017.2.2 (Build 865U)" ts="2021-02-25 11:16:35">
<Class name="Tongji.HQS.MSG.ResponseMessageHeader">
<Super>Ens.Response</Super>
<TimeChanged>64287,32962</TimeChanged>
<TimeCreated>63755,39595.676235</TimeCreated>

<Property name="Sender">
<Type>%String</Type>
</Property>

<Property name="Receiver">
<Type>%String</Type>
</Property>

<Property name="SendTime">
<Type>%String</Type>
</Property>

<Property name="EventType">
<Type>%String</Type>
</Property>

<Property name="MsgId">
<Type>%String</Type>
</Property>

<Storage name="Default">
<Type>%Library.CacheStorage</Type>
<DefaultData>ResponseMessageHeaderDefaultData</DefaultData>
<Data name="ResponseMessageHeaderDefaultData">
<Structure>listnode</Structure>
<Subscript>"ResponseMessageHeader"</Subscript>
<Value name="1">
<Value>Sender</Value>
</Value>
<Value name="2">
<Value>Receiver</Value>
</Value>
<Value name="3">
<Value>SendTime</Value>
</Value>
<Value name="4">
<Value>EventType</Value>
</Value>
<Value name="5">
<Value>MsgId</Value>
</Value>
</Data>
</Storage>
</Class>
</Export>
