<?xml version="1.0" encoding="UTF-8"?>
<Export generator="Cache" version="25" zv="Cache for Windows (x86-64) 2017.2.2 (Build 865U)" ts="2021-02-25 11:16:52">
<Class name="Tongji.HQS.MSG.ResponseMessageBody">
<Super>Ens.Response</Super>
<TimeChanged>64264,60756.451979</TimeChanged>
<TimeCreated>63755,39817.565229</TimeCreated>

<Property name="Result">
<Type>Tongji.HQS.MSG.Result</Type>
</Property>

<Property name="Dataset">
<Type>%GlobalCharacterStream</Type>
<Parameter name="CONTENT" value="MIXED"/>
</Property>

<Storage name="Default">
<Type>%Library.CacheStorage</Type>
<DefaultData>ResponseMessageBodyDefaultData</DefaultData>
<Data name="ResponseMessageBodyDefaultData">
<Subscript>"ResponseMessageBody"</Subscript>
<Value name="1">
<Value>Result</Value>
</Value>
<Value name="2">
<Value>Dataset</Value>
</Value>
</Data>
</Storage>
</Class>
</Export>
